apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample-springboot-app
 labels:
   app: sample-springboot-app
spec:
 selector:
   matchLabels:
     app: sample-springboot-app
 template:
   metadata:
      labels:
        app: sample-springboot-app
   spec:
     containers:
     - image: sample-app:latest
       name: springboot-chat
       imagePullPolicy: IfNotPresent
       ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-springboot-app-svc
spec:
    ports:
    - name: "sample-springboot-app"
      targetPort: 8080
      port: 8080
      nodePort: 30205
      protocol: TCP
    selector:
      app: sample-springboot-app
    type: NodePort

